
["Botany Pots Tiers Options"]
	#
	#Creative Botany Pot Speed
	#Range: > 1
	creativeBotanyPotSpeed = 40
	#
	#Ultra Botany Pot Speed
	#Range: > 1
	ultraBotanyPotSpeed = 20
	#
	#Ultra Botany Pot Multiplier
	#Range: > 1
	ultraBotanyPotMultiplier = 15
	#
	#Elite Botany Pot Speed
	#Range: > 1
	eliteBotanyPotSpeed = 10
	#
	#Elite Botany Pot Multiplier
	#Range: > 1
	eliteBotanyPotMultiplier = 5
	#
	#Creative Botany Pot Multiplier
	#Range: > 1
	creativeBotanyPotMultiplier = 20

